CREATE DATABASE QLBH_BL
GO
USE QLBH_BL
GO
CREATE TABLE NHANVIEN ( 
MANV CHAR(5) NOT NULL,
TENNV NVARCHAR(30) NOT NULL,
SODT VARCHAR(10) NOT NULL,
CONSTRAINT pk_NHANVIEN PRIMARY KEY(MANV)
)
GO
CREATE TABLE KHACHHANG (
MAKH CHAR(5) NOT NULL,
TENKH NVARCHAR(30) NOT NULL,
DIACHI NVARCHAR(100) NOT NULL,
SODT VARCHAR(10) NOT NULL,
CONSTRAINT pk_KHACHHANG PRIMARY KEY(MAKH)
)
GO 
CREATE TABLE SANPHAM (
MASP CHAR(5) NOT NULL,
TENSP NVARCHAR(30) NOT NULL,
GIABAN DECIMAL(18,2) NOT NULL,
CONSTRAINT pk_SANPHAM PRIMARY KEY(MASP) 
)
GO
CREATE TABLE HOADON (
MAHD CHAR(5) NOT NULL,
NGAYLAP DATE NOT NULL,
MAKH CHAR(5) NOT NULL,
MANV CHAR(5) NOT NULL,
CONSTRAINT pK_HOADON PRIMARY KEY(MAHD),
CONSTRAINT fk_hoadon_khachhang FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
CONSTRAINT fk_hoadon_nhanvien FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE CHITIETHOADON (
MAHD CHAR(5) NOT NULL,
MASP CHAR(5) NOT NULL,
SOLUONG INT NOT NULL,
DONGIA DECIMAL(18,2) NOT NULL,
CONSTRAINT pk_CHITIETHOADON PRIMARY KEY (MAHD,MASP),
CONSTRAINT fk_CTHD_HOADON FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
CONSTRAINT fk_CTHD_SANPHAM FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
)


INSERT INTO NHANVIEN (MANV, TENNV, SODT) VALUES 
('NV001', N'Nguyễn Hoàng Phúc', '0901234567'),
('NV002', N'Trần Thị Mai', '0912345678'),
('NV003', N'Lê Văn Tâm', '0987654321'),
('NV004', N'Phạm Minh Duy', '0933445566'),
('NV005', N'Võ Hoàng Yến', '0944556677');

INSERT INTO KHACHHANG (MAKH, TENKH, DIACHI, SODT) VALUES 
('KH001', N'Trần Quốc Bảo', N'Quận 1, TP. HCM', '0909123456'),
('KH002', N'Lê Bảo Châu', N'Quận 7, TP. HCM', '0918223344'),
('KH003', N'Nguyễn Thái Vy', N'Ninh Kiều, Cần Thơ', '0932115566'),
('KH004', N'Hoàng Thanh Hải', N'Thủ Dầu Một, Bình Dương', '0945667788'),
('KH005', N'Đặng Thu Thảo', N'Cái Răng, Cần Thơ', '0977889900');

INSERT INTO SANPHAM (MASP, TENSP, GIABAN) VALUES 
('SP001', N'Bàn ăn gỗ sồi', 5500000),
('SP002', N'Ghế làm việc xoay', 1200000),
('SP003', N'Giường ngủ Queen', 8500000),
('SP004', N'Tủ quần áo 2 cánh', 4200000),
('SP005', N'Đèn bàn đọc sách', 450000);

INSERT INTO HOADON (MAHD, NGAYLAP, MAKH, MANV) VALUES 
('HD001', '2026-04-15', 'KH001', 'NV001'),
('HD002', '2026-04-16', 'KH002', 'NV002'),
('HD003', '2026-04-17', 'KH001', 'NV003'),
('HD004', '2026-04-18', 'KH003', 'NV001'),
('HD005', '2026-04-18', 'KH004', 'NV005');

INSERT INTO CHITIETHOADON(MAHD, MASP, SOLUONG, DONGIA) VALUES
('HD001', 'SP004', 50, 180000), 
('HD001', 'SP001', 1, 5500000), -- Hóa đơn 1 mua thêm Bàn ăn
('HD002', 'SP003', 1, 8500000), -- Hóa đơn 2 mua Giường ngủ
('HD003', 'SP005', 5, 450000),  -- Hóa đơn 3 mua 5 cái Đèn
('HD004', 'SP002', 2, 1200000); -- Hóa đơn 4 mua 2 cái Ghế xoay

SELECT 
    HD.MAHD, 
    KH.TENKH, 
    SP.TENSP, 
    CT.SOLUONG, 
    (CT.SOLUONG*CT.DONGIA) AS THANHTIEN 
FROM CHITIETHOADON CT
JOIN HOADON HD ON CT.MAHD = HD.MAHD
JOIN KHACHHANG KH ON HD.MAKH = KH.MAKH
JOIN SANPHAM SP ON CT.MASP = SP.MASP;

--Phân tích chi tiêu của từng Khách hàng
SELECT 
   KH.TENKH AS TENKHACHHANG,
   COUNT(DISTINCT HD.MAHD) AS SODONDAMUA,
   SUM (CT.SOLUONG*CT.DONGIA) AS TONGGIATRITICHLUY
   FROM KHACHHANG AS KH
   JOIN HOADON AS HD ON KH.MAKH=HD.MAKH
   JOIN CHITIETHOADON AS CT ON HD.MAHD=CT.MAHD
   GROUP BY KH.TENKH
   ORDER BY SUM (CT.SOLUONG*CT.DONGIA) DESC ;

--Top 5 Sản phẩm đem lại doanh thu cao nhất
   SELECT TOP 5
    SP.TENSP AS TENSP,
    SUM(CT.SOLUONG) AS TONGSLBAN,
    SUM(CT.SOLUONG * CT.DONGIA) AS DOANHTHUTHUVE
FROM SANPHAM AS SP
JOIN CHITIETHOADON AS CT ON SP.MASP = CT.MASP
GROUP BY SP.TENSP
ORDER BY DOANHTHUTHUVE DESC

--Tìm hóa đơn có giá trị cao bất thường
SELECT 
HD.MAHD,
HD.NGAYLAP,
SUM(CT.SOLUONG*CT.DONGIA) AS GIATRIHD
FROM HOADON AS HD
JOIN CHITIETHOADON AS CT 
ON HD.MAHD=CT.MAHD
GROUP BY HD.MAHD,HD.NGAYLAP
HAVING SUM(CT.SOLUONG*CT.DONGIA) > 10000000;

--Thêm cột vào bảng
ALTER TABLE HOADON
ADD TRANGTHAI NVARCHAR(50) DEFAULT N'CHUATHANHTOAN';

--Xóa cột
ALTER TABLE HOADON
DROP COLUMN TRANGTHAI;

--Update trạng thái hóa đơn
UPDATE HOADON
SET TRANGTHAI = N'Đã thanh toán'
WHERE MAKH = 'KH001' AND NGAYLAP = CAST(GETDATE() AS DATE);

  
