SELECT MASP, TENSP FROM SANPHAM
WHERE MASP IN('SP001','SP002' ,'SP003')
ORDER BY MASP DESC

SELECT SP.MASP, SP.TENSP, CTHD.DONGIA FROM SANPHAM SP
INNER JOIN CHITIETHOADON CTHD 
ON SP.MASP=CTHD.MASP

SELECT SP.MASP, CTHD.DONGIA FROM SANPHAM SP
INNER JOIN CHITIETHOADON CTHD 
ON SP.MASP=CTHD.MASP
GROUP BY SP.MASP, CTHD.DONGIA

SELECT HD.MAHD, 
SUM(CT.SOLUONG*CT.DONGIA) AS TONGTIENHOADON
FROM CHITIETHOADON AS CT
JOIN HOADON AS HD ON CT.MAHD= HD.MAHD
GROUP BY HD.MAHD


